# Generated by Django 5.0.2 on 2024-03-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cars",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=30)),
                ("package", models.CharField(max_length=30)),
                ("year", models.IntegerField()),
                ("milage", models.IntegerField()),
                ("price", models.IntegerField()),
            ],
        ),
    ]
