# Generated by Django 5.0.2 on 2024-03-03 21:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scrapping", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Cars",
            new_name="Car",
        ),
    ]
