# Generated by Django 5.0.2 on 2024-03-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scrapping", "0002_rename_cars_car"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="vin",
            field=models.CharField(default="default", max_length=17, unique=True),
            preserve_default=False,
        ),
    ]
