# Generated by Django 5.0.2 on 2024-03-11 07:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scrapping", "0003_car_vin"),
    ]

    operations = [
        migrations.RenameField(
            model_name="car",
            old_name="milage",
            new_name="mileage",
        ),
    ]
